### ISSUE TITLE
Where should BEDMS live long-term? 

### ISSUE THREAD

**Issue by nsheff** [databio/bedms#14]
Where should BEDMS live? It has different components:
- code for generic metadata standardizers, architecture (should live in `peppy`?)
- code for how to train these particular models (should live in `scripts/model-training`?)
- trained models (should live on hugging face?)

Are there other components, or are these not the right places?

**Comment by saanikat** [comment]
### Discussion (17 Sep 2024)
`bedms` package can presently stay as an individual repository. 
In the future, `bedms` is going to expand to metadata standardization for other formats as well ( not just BED). There would be a new **Metadata Standardization** package where the models of `bedms` will be stored. The present `attr_standardizer.py` and other BED-specific aspects can then be moved to BEDBOSS.
